### ISSUE TITLE
Type: class to support some kind of mapping or parse function

### ISSUE THREAD

**Issue by ConneXNL** [AmpersandJS/ampersand-dom-bindings#12] opened 2014-08-13 06:30 UTC
I came across an issue where my model has a "status" property that can be  "phase1", "phase2" or "phase3" and my classes are equal but prepend "widget-". When I try to use the bindings to change the class of the view element there is no way to prepend, append or parse the class name.

As a work around I had to poison my models with class properties. In my opinion models should not contain any CSS information so i propose the following syntax to make my usage possible without modifying the models: 

```javascript   
bindings: {
            'model.status' : {
                type: 'class'
                parse: function(status){
                        return "widget-" + class;
                }
            }
}
```

**Comment by pgilad** [comment] 2015-08-30 06:53
Closing this as a duplicate of #13  - It will be resolved there.

**Closed by pgilad** 2015-08-30 06:53 UTC
